#!/usr/bin/env python3
"""
merge_timeline.py — interleave Whisper transcript + described frames into
a raw timestamped timeline markdown file for SOPify.

Usage:
    merge_timeline.py AUDIO_JSON FRAMES_JSON OUT_MD

Args:
    AUDIO_JSON   Whisper output (--output_format json --word_timestamps True).
                 Expected shape: {"segments": [{"start": s, "end": e,
                 "text": "...", "words": [...]}, ...]}
    FRAMES_JSON  Frame manifest with descriptions filled in. Same shape as
                 frames.json from extract_frames.py, with each entry having
                 an added "description" string. Entries missing a description
                 are still included with "(no description)".
    OUT_MD       output markdown path

Output: writes OUT_MD with chronological blocks like:

    ## [00:00:00] Visual
    ![](frames/frame_0001.jpg)
    Visual: User is on the dashboard for XYZ ...

    ## [00:00:02] Narration
    > "So first I'm going to open the dashboard ..."

Image paths in the markdown are relative to OUT_MD's directory if the frame
path lives under that same directory; otherwise the absolute path is used.

No external deps.
"""

import json
import os
import sys


def usage():
    sys.stderr.write(__doc__)
    sys.exit(2)


def fmt_ts(seconds: float) -> str:
    s = int(seconds)
    h = s // 3600
    m = (s % 3600) // 60
    sec = s % 60
    return f"{h:02d}:{m:02d}:{sec:02d}"


def relpath_for_md(frame_path: str, md_dir: str) -> str:
    """Return a path suitable for a markdown image link.

    If frame_path is under md_dir, return the relative path; else absolute.
    """
    try:
        ap = os.path.abspath(frame_path)
        ad = os.path.abspath(md_dir)
        if ap.startswith(ad + os.sep):
            return os.path.relpath(ap, ad)
    except Exception:
        pass
    return frame_path


def main():
    if len(sys.argv) != 4 or sys.argv[1] in ("-h", "--help"):
        usage()

    audio_json_path = sys.argv[1]
    frames_json_path = sys.argv[2]
    out_md_path = sys.argv[3]

    with open(audio_json_path) as f:
        audio = json.load(f)
    with open(frames_json_path) as f:
        frames = json.load(f)

    md_dir = os.path.dirname(os.path.abspath(out_md_path)) or "."

    # Build a unified event list.
    # Each event: ("visual" or "narration", time_seconds, payload)
    events = []

    for fr in frames:
        events.append((
            "visual",
            float(fr.get("time", 0.0)),
            {
                "path": fr.get("path", ""),
                "description": fr.get("description", "(no description)"),
                "index": fr.get("index"),
                "source": fr.get("source", ""),
            },
        ))

    for seg in audio.get("segments", []):
        text = (seg.get("text") or "").strip()
        if not text:
            continue
        events.append((
            "narration",
            float(seg.get("start", 0.0)),
            {
                "text": text,
                "end": float(seg.get("end", 0.0)),
            },
        ))

    # Stable sort by time, with visual sorted before narration at equal times
    # so an opening frame appears before opening narration.
    type_order = {"visual": 0, "narration": 1}
    events.sort(key=lambda e: (e[1], type_order[e[0]]))

    lines = []
    lines.append("# Raw Timeline")
    lines.append("")
    lines.append(
        "_Auto-generated by SOPify. Visual blocks are described frame samples "
        "at scene changes; narration blocks are the verbatim transcript._"
    )
    lines.append("")

    for kind, t, payload in events:
        ts = fmt_ts(t)
        if kind == "visual":
            img_md_path = relpath_for_md(payload["path"], md_dir)
            src = payload.get("source") or ""
            hdr = f"## [{ts}] Visual" + (f"  _(sampled @ {src})_" if src else "")
            lines.append(hdr)
            lines.append(f"![]({img_md_path})")
            lines.append(f"Visual: {payload['description']}")
            lines.append("")
        else:
            lines.append(f"## [{ts}] Narration")
            lines.append(f"> \"{payload['text']}\"")
            lines.append("")

    with open(out_md_path, "w") as f:
        f.write("\n".join(lines))

    n_visual = sum(1 for e in events if e[0] == "visual")
    n_narration = sum(1 for e in events if e[0] == "narration")
    sys.stderr.write(
        f"sopify/merge_timeline: wrote {n_visual} visual + {n_narration} "
        f"narration blocks -> {out_md_path}\n"
    )
    print(out_md_path)


if __name__ == "__main__":
    main()
